### PR TITLE
Implemented inter-key-delay

### PR DESCRIPTION
**Pull request by GhostPHX**
and added it to the documentation. Writing procdure (which was not included in the doc) has also been added

---
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/kbdwtchdg/6)

### CODE REVIEW

**Comment by 7enderhead** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/main.rst, line 200 at r1](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6#-KsmlCrCMx4jVcJpOeb0:-KsmlCrCMx4jVcJpOeb1:b-7le1c8) ([raw file](https://github.com/7enderhead/kbdwtchdg/blob/e889396f32493dfc6f01a4148ef9fb3df3a17a83/doc/main.rst#L200)):*
> ```reStructuredText
>     #define TEXT PSTR("Hello World! This is kbdwatchdog!\n") //Text to be written
>     
>     #define INTER_KEY_DELAY 100 // delay between key presses in milliseconds
> ```

Describe that to use no INTER_KEY_DELAY, commenting out of the line needs to be done.

---

*[doc/main.rst, line 344 at r1](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6#-Ksml15l_9SRSt5rwhzS:-Ksml15mN9Y6U7kzYurB:br9qsaq) ([raw file](https://github.com/7enderhead/kbdwtchdg/blob/e889396f32493dfc6f01a4148ef9fb3df3a17a83/doc/main.rst#L344)):*
> ```reStructuredText
> *****************
> 
> The writing prodecure consists of turning the RED LED on (to indicate writinng) and writing the defined text.
> ```

'writinng' -> 'writing'

---

*[doc/main.rst, line 347 at r1](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6#-Ksml8AxRjIvqAn-XPQh:-Ksml8AxRjIvqAn-XPQi:bzepims) ([raw file](https://github.com/7enderhead/kbdwtchdg/blob/e889396f32493dfc6f01a4148ef9fb3df3a17a83/doc/main.rst#L347)):*
> ```reStructuredText
> 
> Afterwards ``timer_count``, ``blink_count`` and ``delay startet`` are reset,
> ``first_start`` is set to false (0).
> ```

Explain why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6)*

**Comment by 7enderhead** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6)*

**Comment by GhostPHX** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/main.rst, line 200 at r1](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6#-KsmlCrCMx4jVcJpOeb0:-KsmoQ-k5cNhMeACiXdX:bs8k86l) ([raw file](https://github.com/7enderhead/kbdwtchdg/blob/e889396f32493dfc6f01a4148ef9fb3df3a17a83/doc/main.rst#L200)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

Describe that to use no INTER_KEY_DELAY, commenting out of the line needs to be done.
</blockquote></details>

Improved description

---

*[doc/main.rst, line 344 at r1](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6#-Ksml15l_9SRSt5rwhzS:-KsmoLl4L03gLyOVYCqP:b7qwr4q) ([raw file](https://github.com/7enderhead/kbdwtchdg/blob/e889396f32493dfc6f01a4148ef9fb3df3a17a83/doc/main.rst#L344)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

'writinng' -> 'writing'
</blockquote></details>

Fixed in next commit

---

*[doc/main.rst, line 347 at r1](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6#-Ksml8AxRjIvqAn-XPQh:-KsmpNLCXzAI_Q3PH4e_:bywhcj8) ([raw file](https://github.com/7enderhead/kbdwtchdg/blob/e889396f32493dfc6f01a4148ef9fb3df3a17a83/doc/main.rst#L347)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

Explain why.
</blockquote></details>

Explanation added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6)*

**Comment by 7enderhead** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/6)*

**Pull request merged**
