### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by GhostPHX**
Reworked documentation

---
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/kbdwtchdg/1)

### CODE REVIEW

**Comment by 7enderhead** [comment]
Review status: 0 of 88 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/main.html, line 3 at r2](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/1#-KrjjyxiX1na4fax0nmI:-KrjjyxjKMuke7I2f94h:b4vlk2q) ([raw file](https://github.com/7enderhead/kbdwtchdg/blob/17e7f2575ce6bc1bf2ca071ce07e170eb13e29c9/docs/main.html#L3)):*
> ```HTML
> 
> 
> <!DOCTYPE html>
> ```

Remove all Spinx output from the doc directory, so that only the sources are present.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/1)*

**Comment by 7enderhead** [comment]
Reviewed 72 of 88 files at r1, 16 of 18 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/1)*

**Comment by GhostPHX** [comment]
Review status: 34 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/main.html, line 3 at r2](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/1#-KrjjyxiX1na4fax0nmI:-KrnvTx_TZwPMeJmH9_r:b-896fix) ([raw file](https://github.com/7enderhead/kbdwtchdg/blob/17e7f2575ce6bc1bf2ca071ce07e170eb13e29c9/docs/main.html#L3)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

Remove all Spinx output from the doc directory, so that only the sources are present.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/1)*

**Comment by 7enderhead** [comment]
Reviewed 13 of 59 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/kbdwtchdg/1)*

**Pull request merged**
